# https://github.com/firebase/firebase-tools

name: Deploy For Testing Purposes
on:
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  build_and_deploy:
    name: Deploy on Firebase
    runs-on: macos-latest
    environment: test
    env:
      CONTENTFUL_ACCESS_TOKEN: '${{ secrets.CONTENTFUL_ACCESS_TOKEN }}'
      CONTENTFUL_SPACE_ID: '${{ secrets.CONTENTFUL_SPACE_ID }}'
    steps:
      - name: 🏗 Setup Repo
        uses: actions/checkout@v3
      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
      - name: 📦 Install Dependencies and Build
        run: npm ci && npm run build
      - name: 🚀 Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRESCOM_CORPORATION_GROUP_TEST }}'
          channelId: live
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
          target: '${{ secrets.FIREBASE_TARGET }}'
